services:
  threadsclip:
    image: ghcr.io/jasonheo1125/threadsclip-v1:latest
    container_name: threadsclip
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    restart: unless-stopped
    environment:
      - NODE_ENV=production
